name: Auto Update

on:
  schedule:
    - cron: '0 0 * * 1' # Runs at 12:00 AM UTC every Monday
  workflow_dispatch:
    inputs:
      force:
        description: Force Update
        default: '0'
      dry:
        description: Dry Run
        default: '0'
      bump:
        type: choice
        description: Bump Version
        options:
          - patch
          - minor
          - major

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: git-actions/set-user@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - id: update
        run: |
          output_file="${GITHUB_OUTPUT:-/tmp/github_output}"
          force="${{ github.event.inputs.force }}"
          dry="${{ github.event.inputs.dry }}"
          bump="${{ github.event.inputs.bump }}"
          if [ "$bump" = "" ]; then
            bump="patch"
          fi

          # Check for Updates
          status=0
          bun run check || status=$?
          if [ $status -eq 0 ] || [ $status -eq 4 ]; then
            if [ "$force" != "1" ]; then
              echo "trigger_release=no" >> "$output_file"
              exit 0 # exit if there are no changes or if icons are only removed
            fi
          fi
          if [ $status -ge 4 ]; then
            bump="minor" # icons are removed from metadata API
          fi

          # Download new metadata
          bun run download:metadata
          bun run generate:wrappers
          git add .

          # Bump Version
          npm version "$bump" -m "build: auto update to v%s" --force

          # Push
          if [ "$dry" = "1" ]; then
            echo "trigger_release=no" >> "$output_file"
            exit 0
          fi
          git push --follow-tags
          echo "trigger_release=yes" >> "$output_file"
    outputs:
      trigger_release: ${{ steps.update.outputs.trigger_release }}

  conditional-workflow:
    runs-on: ubuntu-latest
    needs: update
    if: needs.update.outputs.trigger_release == 'yes'

    steps:
      - name: Trigger Release
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Release
